arrowParens: always
bracketSpacing: true
jsxSingleQuote: true
printWidth: 100
quoteProps: as-needed
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
endOfLine: auto
semi: true
importOrder: [
    "<THIRD_PARTY_MODULES>",
    "^[@/]",
    "^[./]"
]
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderParserPlugins: ["typescript", "decorators-legacy", "jsx"]
